[package]
name = "two"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"]}
tokio.workspace = true